services:
  - type: web
    name: cash-calendar-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: DATABASE_URL # Gets this from the database service below
        fromDatabase:
          name: cash_calendar_db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        fromSecret: true
      - key: GOOGLE_CLIENT_SECRET
        fromSecret: true
      - key: JWT_SECRET_KEY
        fromSecret: true
      - key: FRONTEND_URL
        fromEnv: RENDER_EXTERNAL_URL # Automatically uses your Netlify URL

databases:
  - name: cash_calendar_db
    databaseName: cash_calendar_db
    plan: free
